apiVersion: v1
kind: Pod
metadata:
  name: busybox-configmap
  namespace: default
spec:
  containers:
  - image: busybox
    name: busy-configmap
    command:
      - sleep
      - "3600"
    env:
    - name: config-dbs
      valueFrom:
        configMapKeyRef:
          name: config-dbs
          key: postgresql.conf
