apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: replica-set-day3
spec:
  replicas: 3
  template:
    metadata:
      labels:
        system: Giropops
    specs:
      containers:
      - name: nginx
        image: nginx:1.7.9
        ports:
        - containerPort: 80
