apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: primeiro-pvc
spec:
  storageClassName: ""
  accessModes:
  - ReadWriteMany
  selector:
    matchLabels:
      type: "giropops"
  resources:
    requests:
      storage: 800Mi
